// Generated by scripts/area-reference.ts (npm run calibrate) from 300 seeded perfect shuffles per size. Don't edit by hand.
import type { Area } from './metrics.ts'

/** A perfect shuffle's average worst degree in each area, per deck size: all tests, and noticeable failures only. */
export const AREA_REFERENCE: Record<number, Record<Area, { degree: number; noticed: number }>> = {
  "52": {
    "order": {
      "degree": 0.03161227285228313,
      "noticed": 0.023266784206113413
    },
    "proximity": {
      "degree": 0.3631202014623928,
      "noticed": 0.009037558676361308
    },
    "position": {
      "degree": 0.3701982053720442,
      "noticed": 0.1653221430073738
    },
    "grouping": {
      "degree": 0.2376347663534647,
      "noticed": 0.011450132307509277
    },
    "holistic": {
      "degree": 0.10675925925925907,
      "noticed": 0
    }
  },
  "60": {
    "order": {
      "degree": 0.028952078366626156,
      "noticed": 0.020698213265574677
    },
    "proximity": {
      "degree": 0.37572739258102383,
      "noticed": 0.009770776070603941
    },
    "position": {
      "degree": 0.3987849544439276,
      "noticed": 0.17249795536012008
    },
    "grouping": {
      "degree": 0.22766288038660237,
      "noticed": 0.008976709485693672
    },
    "holistic": {
      "degree": 0.10592592592592576,
      "noticed": 0
    }
  },
  "99": {
    "order": {
      "degree": 0.030360580250987947,
      "noticed": 0.02188046860247031
    },
    "proximity": {
      "degree": 0.3707479418640773,
      "noticed": 0.009325715724020078
    },
    "position": {
      "degree": 0.3585718481478888,
      "noticed": 0.13254863236503459
    },
    "grouping": {
      "degree": 0.23325269924103342,
      "noticed": 0.008886637234899105
    },
    "holistic": {
      "degree": 0.10527777777777766,
      "noticed": 0
    }
  }
}
