// Generated by scripts/calibrate.ts (npm run calibrate) from 1000000 seeded random decks per size. Don't edit by hand.
import type { Base } from './calibrate.ts'

export const CALIBRATION_DECKS = 1000000

export const BASELINES: Record<number, Base> = {
  "52": {
    "ordering": {
      "mean": 26.49984,
      "standardDeviation": 2.1010678176584694,
      "threshold": 6.303203452975408
    },
    "proximity": {
      "mean": 5.770466,
      "standardDeviation": 2.2590245998757963,
      "threshold": 12.547539799627389,
      "high": 12.547539799627389,
      "low": 5.291254515968179
    },
    "drift": {
      "mean": 16.668476843137135,
      "standardDeviation": 1.5086150163039813,
      "threshold": 16.988502415605655,
      "high": 16.988502415605655,
      "low": 16.348451270668615
    },
    "gaps": {
      "mean": 21.628893883114333,
      "standardDeviation": 6.5442937833882615,
      "threshold": 41.26177523327912
    },
    "corr": {
      "mean": -0.01980790166419426,
      "standardDeviation": 0.13884617139835675,
      "threshold": 0.41653851419507026
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "threshold": 0.56
    },
    "chain": {
      "mean": 4.198834,
      "standardDeviation": 0.7897727777304069,
      "threshold": 6.56815233319122
    },
    "strided": {
      "mean": 2.394074,
      "standardDeviation": 0.5017187284963566,
      "threshold": 3.8992301854890696
    },
    "gradient": {
      "mean": 0.00036228846153852463,
      "standardDeviation": 0.002690115321583335,
      "threshold": 0.00843263442628853
    },
    "spacing": {
      "mean": 1.7207025274905687,
      "standardDeviation": 0.352410633191327,
      "threshold": 1.057231899573981
    },
    "clump": {
      "mean": 5.7557304157148925,
      "standardDeviation": 1.8163427593673256,
      "threshold": 6.205252314452595,
      "high": 6.205252314452595,
      "low": 5.30620851697719
    },
    "endret": {
      "mean": 0.15384615384615385,
      "standardDeviation": 0.3768445758127966,
      "threshold": 0.05652668637191949
    },
    "position": {
      "mean": 2601,
      "standardDeviation": 72.12489168102785,
      "threshold": 3771.45
    }
  },
  "60": {
    "ordering": {
      "mean": 30.503382,
      "standardDeviation": 2.256142407312992,
      "threshold": 6.768427221938976
    },
    "proximity": {
      "mean": 5.793806,
      "standardDeviation": 2.282828516197395,
      "threshold": 12.642291548592185,
      "high": 12.642291548592185,
      "low": 5.30954494277324
    },
    "drift": {
      "mean": 19.331182983050258,
      "standardDeviation": 1.622788293468556,
      "threshold": 19.675428365072786,
      "high": 19.675428365072786,
      "low": 18.98693760102773
    },
    "gaps": {
      "mean": 25.700212429813572,
      "standardDeviation": 7.179801055592832,
      "threshold": 47.23961559659207
    },
    "corr": {
      "mean": -0.0167358870774846,
      "standardDeviation": 0.12938217389526557,
      "threshold": 0.3881465216857967
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "threshold": 0.56
    },
    "chain": {
      "mean": 4.288282,
      "standardDeviation": 0.7823346397009412,
      "threshold": 6.635285919102824
    },
    "strided": {
      "mean": 2.394874,
      "standardDeviation": 0.5000285233104205,
      "threshold": 3.8949595699312614
    },
    "gradient": {
      "mean": 0.00027263333333340986,
      "standardDeviation": 0.0021647694152291813,
      "threshold": 0.006766941579020954
    },
    "spacing": {
      "mean": 1.7653621661878027,
      "standardDeviation": 0.3388864655882879,
      "threshold": 1.0166593967648636
    },
    "clump": {
      "mean": 5.918969843137453,
      "standardDeviation": 1.7304076084514655,
      "threshold": 6.347223877090943,
      "high": 6.347223877090943,
      "low": 5.490715809183963
    },
    "endret": {
      "mean": 0.13333333333333333,
      "standardDeviation": 0.35276684147527876,
      "threshold": 0.052915026221291815
    },
    "position": {
      "mean": 3481,
      "standardDeviation": 83.43860018001261,
      "threshold": 5047.45
    }
  },
  "99": {
    "ordering": {
      "mean": 50.001833,
      "standardDeviation": 2.889031609399804,
      "threshold": 8.667094828199412
    },
    "proximity": {
      "mean": 5.87875,
      "standardDeviation": 2.348407638699039,
      "threshold": 12.923972916097117,
      "high": 12.923972916097117,
      "low": 5.380577510105686
    },
    "drift": {
      "mean": 32.33177758163203,
      "standardDeviation": 2.088650295228039,
      "threshold": 32.77484721781694,
      "high": 32.77484721781694,
      "low": 31.888707945447123
    },
    "gaps": {
      "mean": 40.5775212352845,
      "standardDeviation": 9.022720959436182,
      "threshold": 67.64568411359305
    },
    "corr": {
      "mean": -0.010162745890004172,
      "standardDeviation": 0.10055837130600866,
      "threshold": 0.301675113918026
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "threshold": 0.56
    },
    "chain": {
      "mean": 4.592877,
      "standardDeviation": 0.7668453969810352,
      "threshold": 6.893413190943106
    },
    "strided": {
      "mean": 2.394342,
      "standardDeviation": 0.49558085822194564,
      "threshold": 3.881084574665837
    },
    "gradient": {
      "mean": 0.00010105050505050777,
      "standardDeviation": 0.0010199479623658181,
      "threshold": 0.0031608943921479617
    },
    "spacing": {
      "mean": 1.80674239821458,
      "standardDeviation": 0.27202947032666275,
      "threshold": 0.8160884109799882
    },
    "clump": {
      "mean": 6.361193499479625,
      "standardDeviation": 1.4021685497667882,
      "threshold": 6.708212510946936,
      "high": 6.708212510946936,
      "low": 6.014174488012314
    },
    "endret": {
      "mean": 0.08080808080808081,
      "standardDeviation": 0.278465631355358,
      "threshold": 0.04176984470330371
    },
    "position": {
      "mean": 9604,
      "standardDeviation": 138.59292911256333,
      "threshold": 13925.8
    }
  }
}
