// Generated by scripts/calibrate.ts (npm run calibrate) from 1000 seeded batches of 1200 random decks per
// size. Don't edit by hand.
import type { Base } from './calibrate.ts'

export const CALIBRATION_BATCHES = 1000

export const BASELINES: Record<number, Base> = {
  "52": {
    "sequence": {
      "mean": 0.0019407516339869264,
      "standardDeviation": 0.0014359612449907607,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.007043304424333833,
      "standardDeviation": 0.0011705868661907692,
      "sorted": 0.9615384615384615
    },
    "spread": {
      "mean": 0.05574224358974357,
      "standardDeviation": 0.004816120176020804,
      "sorted": 0.9038461538461542
    },
    "ends": {
      "mean": 0.07675583333333345,
      "standardDeviation": 0.005302648777382721,
      "sorted": 1
    },
    "lands": {
      "mean": 0.005547482078741342,
      "standardDeviation": 0.001749751989113896,
      "sorted": 0.5961538461538411
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  },
  "60": {
    "sequence": {
      "mean": 0.0018071751412429365,
      "standardDeviation": 0.0014010630933481833,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.007099548022598872,
      "standardDeviation": 0.0010998292463338952,
      "sorted": 0.9666666666666667
    },
    "spread": {
      "mean": 0.056899166666666744,
      "standardDeviation": 0.004997021065102755,
      "sorted": 0.9000000000000004
    },
    "ends": {
      "mean": 0.0666383333333332,
      "standardDeviation": 0.00501134182432346,
      "sorted": 1
    },
    "lands": {
      "mean": 0.005305550347140639,
      "standardDeviation": 0.0016308146593351533,
      "sorted": 0.5999999999999995
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  },
  "99": {
    "sequence": {
      "mean": 0.0013782482993197288,
      "standardDeviation": 0.0010122388271105746,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.006736325499896928,
      "standardDeviation": 0.0008706999866039363,
      "sorted": 0.9797979797979798
    },
    "spread": {
      "mean": 0.058763030303030296,
      "standardDeviation": 0.004835328580547712,
      "sorted": 0.9090909090909091
    },
    "ends": {
      "mean": 0.040371666666666646,
      "standardDeviation": 0.003851582101511617,
      "sorted": 1
    },
    "lands": {
      "mean": 0.004101519025008719,
      "standardDeviation": 0.001283217955921993,
      "sorted": 0.5959595959595959
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  }
}
