// Generated by scripts/calibrate.ts (npm run calibrate) from 1000 seeded batches of 1200 random decks per
// size. Don't edit by hand.
import type { Base } from './calibrate.ts'

export const CALIBRATION_BATCHES = 1000

export const BASELINES: Record<number, Base> = {
  "52": {
    "sequence": {
      "mean": 0.037152957253662834,
      "standardDeviation": 0.004611521993475788,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.007043304424333833,
      "standardDeviation": 0.0011705868661907692,
      "sorted": 0.9615384615384615
    },
    "position": {
      "mean": 0.03744977591541485,
      "standardDeviation": 0.0013939722144873962,
      "sorted": 0.8995169148009309
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  },
  "60": {
    "sequence": {
      "mean": 0.03743479643413356,
      "standardDeviation": 0.0042217906274403475,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.007099548022598872,
      "standardDeviation": 0.0010998292463338952,
      "sorted": 0.9666666666666667
    },
    "position": {
      "mean": 0.037625303139465244,
      "standardDeviation": 0.0012961793754893728,
      "sorted": 0.9000000000000006
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  },
  "99": {
    "sequence": {
      "mean": 0.03770931314233977,
      "standardDeviation": 0.0032080653612105076,
      "sorted": 1
    },
    "proximity": {
      "mean": 0.006736325499896928,
      "standardDeviation": 0.0008706999866039363,
      "sorted": 0.9797979797979798
    },
    "position": {
      "mean": 0.037624514465049164,
      "standardDeviation": 0.0010026609861055959,
      "sorted": 0.8999223137852403
    },
    "classifier": {
      "mean": 0.5,
      "standardDeviation": 0.02,
      "sorted": 1
    }
  }
}
