// Measure what a perfect shuffle reads in each area, and store it in src/engine/areaReference.ts.
// An area's degree is its worst test's degree, and the worst of more noisy readings is higher, so an area with five
// tests reads higher on a random deck than an area with two. Subtracting these averages puts every area on the same
// footing: an excess of 0 means "as random as a perfect shuffle". Only the search's excess figures use this; no test
// does, so it isn't part of the engine fingerprint.
//
// Runs after scripts/calibrate.ts, because it judges against the stored baselines. Usage: npm run calibrate
import { writeFileSync } from 'node:fs'
import { parseArgs } from 'node:util'
import { DECK_SIZES, fisher } from '../src/engine/decks.ts'
import { AREA_LABELS, type Area } from '../src/engine/metrics.ts'
import { areaReadings } from '../src/engine/scoring.ts'
import { computeResult } from '../src/engine/simulate.ts'

const { values } = parseArgs({ options: { runs: { type: 'string', default: '300' } } })
const runs = Number(values.runs)

/** A seeded stand-in for Math.random (mulberry32), so the reference can be regenerated exactly. */
function seed(state: number) {
  Math.random = () => {
    state = (state + 0x6d2b79f5) | 0
    let value = Math.imul(state ^ (state >>> 15), 1 | state)
    value = (value + Math.imul(value ^ (value >>> 7), 61 | value)) ^ value
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296
  }
}

const reference: Record<number, Record<Area, { degree: number; noticed: number }>> = {}
for (const { value: deckSize } of DECK_SIZES) {
  seed(deckSize + 1)
  const started = Date.now()
  const sums = Object.fromEntries(AREA_LABELS.map(([area]) => [area, { degree: 0, noticed: 0 }])) as Record<Area, { degree: number; noticed: number }>
  for (let run = 0; run < runs; run++) {
    const result = computeResult('sorted', deckSize, ['mash'], 'ends', (deck) => fisher(deck.length))
    const readings = areaReadings(result.avg, result.base, result.moveCount, deckSize)
    for (const [area] of AREA_LABELS) {
      sums[area].degree += readings[area].degree / runs
      sums[area].noticed += readings[area].noticed / runs
    }
  }
  reference[deckSize] = sums
  const summary = AREA_LABELS.map(([area, label]) => `${label} ${sums[area].degree.toFixed(2)}/${sums[area].noticed.toFixed(2)}`).join(', ')
  console.log(`${deckSize} cards: ${runs} perfect shuffles in ${Date.now() - started}ms. Average worst degree (all/noticeable): ${summary}.`)
}

const source = `// Generated by scripts/area-reference.ts (npm run calibrate) from ${runs} seeded perfect shuffles per size. Don't edit by hand.
import type { Area } from './metrics.ts'

/** A perfect shuffle's average worst degree in each area, per deck size: all tests, and noticeable failures only. */
export const AREA_REFERENCE: Record<number, Record<Area, { degree: number; noticed: number }>> = ${JSON.stringify(reference, null, 2)}
`
writeFileSync('src/engine/areaReference.ts', source)
console.log('Wrote src/engine/areaReference.ts.')
