// Calibrate each metric's baseline once, from a large seeded sample, and store it in src/engine/baselines.ts. Every run
// then reads its levels against the same baselines.
//
// Usage: npm run calibrate -- [--batches 1000]
import { writeFileSync } from 'node:fs'
import { parseArgs } from 'node:util'
import { calibrate } from '../src/engine/calibrate.ts'
import { DECK_SIZES } from '../src/engine/decks.ts'
import { RUN_DECKS } from '../src/engine/metrics/types.ts'
import { seed } from '../src/engine/seeded.ts'

const { values } = parseArgs({ options: { batches: { type: 'string', default: '1000' } } })
const batchCount = Number(values.batches)

const baselines: Record<number, ReturnType<typeof calibrate>> = {}
for (const { value: deckSize } of DECK_SIZES) {
  seed(deckSize)
  const started = Date.now()
  baselines[deckSize] = calibrate(deckSize, batchCount)
  console.log(`${deckSize} cards: ${batchCount} batches in ${Date.now() - started}ms.`)
  for (const [key, baseline] of Object.entries(baselines[deckSize])) {
    const noise = (3 * baseline.standardDeviation) / Math.abs(baseline.sorted - baseline.mean)
    console.log(`  ${key.padEnd(11)} random ${baseline.mean.toFixed(4)} ± ${baseline.standardDeviation.toFixed(4)}, sorted ${baseline.sorted.toFixed(4)}, noise level ${noise.toFixed(3)}`)
  }
}

const source = `// Generated by scripts/calibrate.ts (npm run calibrate) from ${batchCount} seeded batches of ${RUN_DECKS} random decks per
// size. Don't edit by hand.
import type { Base } from './calibrate.ts'

export const CALIBRATION_BATCHES = ${batchCount}

export const BASELINES: Record<number, Base> = ${JSON.stringify(baselines, null, 2)}
`
writeFileSync('src/engine/baselines.ts', source)
console.log('Wrote src/engine/baselines.ts.')
