// Calibrate the random-deck baselines once, from a large seeded sample, and store them in src/engine/baselines.ts.
// Every run then judges against the same pass lines. Calibrating on each start from 400 decks moved proximity's lower
// edge by about 0.3 between starts, which flipped routines near that edge between passing and failing.
//
// Usage: npm run calibrate -- [--decks 1000000]
import { writeFileSync } from 'node:fs'
import { parseArgs } from 'node:util'
import { calibrate } from '../src/engine/calibrate.ts'
import { DECK_SIZES } from '../src/engine/decks.ts'
import { seed } from '../src/engine/seeded.ts'

const { values } = parseArgs({ options: { decks: { type: 'string', default: '1000000' } } })
const deckCount = Number(values.decks)

const baselines: Record<number, ReturnType<typeof calibrate>> = {}
for (const { value: deckSize } of DECK_SIZES) {
  seed(deckSize)
  const started = Date.now()
  baselines[deckSize] = calibrate(deckSize, deckCount)
  const proximity = baselines[deckSize].proximity
  console.log(`${deckSize} cards: ${deckCount} decks in ${Date.now() - started}ms. Proximity band ${proximity.low!.toFixed(3)} to ${proximity.high!.toFixed(3)}.`)
}

const source = `// Generated by scripts/calibrate.ts (npm run calibrate) from ${deckCount} seeded random decks per size. Don't edit by hand.
import type { Base } from './calibrate.ts'

export const CALIBRATION_DECKS = ${deckCount}

export const BASELINES: Record<number, Base> = ${JSON.stringify(baselines, null, 2)}
`
writeFileSync('src/engine/baselines.ts', source)
console.log('Wrote src/engine/baselines.ts.')
